#!/bin/sh
CUR_DIR=$PWD
OUTPUT_DIR=$PWD/ArduinoFlatCC
rm -rf $OUTPUT_DIR && \
mkdir -p $OUTPUT_DIR/src && \
rm -rf tmp && \
mkdir -p tmp && \
cd tmp && \
git clone git@github.com:dvidelabs/flatcc.git && \
cp -R flatcc/include/flatcc $OUTPUT_DIR/src && \
cp flatcc/LICENSE $OUTPUT_DIR && \
cp flatcc/src/runtime/*.c $OUTPUT_DIR/src

FLATCC_VERSION=$(grep FLATCC_VERSION_TEXT flatcc/include/flatcc/flatcc_version.h | egrep -oh '"(.*?)"' | cut -d '"' -f2)
cd $OUTPUT_DIR

cat <<EOF > library.properties
name=ArduioFlatCC
version=$FLATCC_VERSION
author=dvidelabs
maintainer=rimim
sentence=Arduino version of flatcc
paragraph=FlatBuffers implementation flatcc packaged for Arduino
catagory=Communications
url=https://github.com/rimim/ArduinoFlatCC
EOF

cat <<EOF > src/ArduinoFlatCC.h
#include "flatcc/flatcc.h"
EOF

cat <<EOF > README.md
Autogenerated from https://github.com/dvidelabs/flatcc using ArduinoFlatCCGen
EOF

cd $CUR_DIR
rm -rf tmp
